#!/usr/bin/env python3
"""Solve a finite-angle steady state on the sparse ``(E,J)`` jump operator.

The operator is generated by ``finite_angle_capture.py``.  Every phase-space
cell is split into an internal state and a state whose exact Kepler apocentre
crosses the reporting surface.  Reservoir-connected states are fixed to the
fluid distribution, while internal occupation factors are solved from zero net
population current.  This is a development solver: an accepted absolute current
still requires resolution, seed, reporting-surface, and production-snapshot
convergence.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import ej_energy_ledger
from scipy.optimize import least_squares

POST_RESERVOIR = -2
POST_CAPTURE = -1


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_operator(path: Path) -> Tuple[Dict[str, np.ndarray], dict]:
    with np.load(path, allow_pickle=False) as archive:
        arrays = {key: archive[key] for key in archive.files if key != "metadata_json"}
        metadata = json.loads(str(archive["metadata_json"]))
    if metadata.get("schema") != "finite-angle-ej-jump-operator-v1":
        raise RuntimeError("unsupported EJ operator schema")
    required = {
        "source1", "source2", "pre", "post",
        "rate_direct_msun_per_myr", "rate_immediate_msun_per_myr",
        "sample_count", "x_edges", "j_over_jlc_edges",
    }
    missing = required - arrays.keys()
    if missing:
        raise RuntimeError(f"EJ operator is missing arrays: {sorted(missing)}")
    nrecords = arrays["source1"].size
    if any(arrays[key].size != nrecords for key in (
        "source2", "pre", "post", "rate_direct_msun_per_myr",
        "rate_immediate_msun_per_myr", "sample_count",
    )):
        raise RuntimeError("EJ operator record arrays have inconsistent lengths")
    energy_keys = (
        "rate_direct_binding_msun_kms2_per_myr",
        "rate_immediate_binding_msun_kms2_per_myr",
    )
    present = tuple(key in arrays for key in energy_keys)
    if any(present) and not all(present):
        raise RuntimeError("EJ operator contains only one capture-energy column")
    if all(present) and any(arrays[key].size != nrecords for key in energy_keys):
        raise RuntimeError("EJ capture-energy arrays have inconsistent lengths")
    return arrays, metadata


def population_rate(
    occupation: np.ndarray,
    source1: np.ndarray,
    source2: np.ndarray,
    pre: np.ndarray,
    post: np.ndarray,
    rate: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return represented-state rates and weighted transition rates."""

    flux = rate * occupation[source1] * occupation[source2]
    dot = -np.bincount(pre, weights=flux, minlength=occupation.size)
    represented = post >= 0
    dot += np.bincount(
        post[represented], weights=flux[represented], minlength=occupation.size
    )
    return dot, flux


def solve_model(
    arrays: Dict[str, np.ndarray],
    metadata: dict,
    model: str,
    occupation_floor: float = 1.0e-30,
    occupation_upper: float = math.exp(5.0),
    rate_floor_fraction: float = 1.0e-12,
    residual_tolerance: float = 1.0e-7,
    maximum_evaluations: int = 5000,
) -> Tuple[dict, np.ndarray]:
    """Solve one capture prescription and return diagnostics and occupations."""

    rate_key = {
        "direct": "rate_direct_msun_per_myr",
        "immediate": "rate_immediate_msun_per_myr",
    }.get(model)
    energy_key = {
        "direct": "rate_direct_binding_msun_kms2_per_myr",
        "immediate": "rate_immediate_binding_msun_kms2_per_myr",
    }.get(model)
    if rate_key is None:
        raise ValueError("model must be direct or immediate")
    if not (0.0 <= occupation_floor < occupation_upper):
        raise ValueError("occupation bounds are not ordered")
    nstates = int(metadata["state_count"])
    source1 = np.asarray(arrays["source1"], np.int64)
    source2 = np.asarray(arrays["source2"], np.int64)
    pre = np.asarray(arrays["pre"], np.int64)
    post = np.asarray(arrays["post"], np.int64)
    rate = np.asarray(arrays[rate_key], float)
    capture_energy_rate = (
        np.asarray(arrays[energy_key], float)
        if energy_key in arrays else None
    )
    if (
        np.any(source1 < 0) or np.any(source1 >= nstates)
        or np.any(source2 < 0) or np.any(source2 >= nstates)
        or np.any(pre < 0) or np.any(pre >= nstates)
        or np.any(post < POST_RESERVOIR) or np.any(post >= nstates)
        or np.any(rate < 0.0) or np.any(~np.isfinite(rate))
        or (
            capture_energy_rate is not None
            and (
                np.any(capture_energy_rate < 0.0)
                or np.any(~np.isfinite(capture_energy_rate))
            )
        )
    ):
        raise RuntimeError("EJ operator contains invalid state indices or rates")

    connected = np.arange(nstates) % 2 == 1
    interaction_scale = np.bincount(pre, weights=rate, minlength=nstates)
    represented = post >= 0
    interaction_scale += np.bincount(
        post[represented], weights=rate[represented], minlength=nstates
    )
    floor = max(float(np.max(interaction_scale)) * rate_floor_fraction, 1.0e-300)
    active = (~connected) & (interaction_scale > floor)
    active_states = np.flatnonzero(active)
    if active_states.size == 0:
        raise RuntimeError("EJ operator has no active internal states")
    active_column = np.full(nstates, -1, dtype=np.int64)
    active_column[active_states] = np.arange(active_states.size)
    scale = interaction_scale[active_states]
    pre_row = active_column[pre]
    post_row = np.full(post.shape, -1, dtype=np.int64)
    post_row[represented] = active_column[post[represented]]

    def occupation_from_active(active_occupation: np.ndarray) -> np.ndarray:
        occupation = np.ones(nstates)
        occupation[active_states] = active_occupation
        return occupation

    def residual(active_occupation: np.ndarray) -> np.ndarray:
        occupation = occupation_from_active(active_occupation)
        dot, _ = population_rate(
            occupation, source1, source2, pre, post, rate
        )
        return dot[active_states] / scale

    def jacobian(active_occupation: np.ndarray) -> np.ndarray:
        occupation = occupation_from_active(active_occupation)
        jac = np.zeros((active_states.size, active_states.size))
        for source, other in ((source1, source2), (source2, source1)):
            column = active_column[source]
            derivative = rate * occupation[other]
            valid_loss = (pre_row >= 0) & (column >= 0)
            np.add.at(
                jac,
                (pre_row[valid_loss], column[valid_loss]),
                -derivative[valid_loss],
            )
            valid_gain = (post_row >= 0) & (column >= 0)
            np.add.at(
                jac,
                (post_row[valid_gain], column[valid_gain]),
                derivative[valid_gain],
            )
        jac /= scale[:, None]
        return jac

    solution = least_squares(
        residual,
        np.ones(active_states.size),
        jac=jacobian,
        bounds=(occupation_floor, occupation_upper),
        method="dogbox",
        x_scale="jac",
        xtol=1.0e-12,
        ftol=1.0e-12,
        gtol=1.0e-12,
        max_nfev=maximum_evaluations,
    )
    active_solution = solution.x.copy()
    optimizer_messages = [f"bounded dogbox: {solution.message}"]
    function_evaluations = int(solution.nfev)
    refinement_success = True
    initial_residual = residual(active_solution)
    if float(np.max(np.abs(initial_residual))) > residual_tolerance:
        pinned = (
            (active_solution <= max(10.0 * occupation_floor, 1.0e-300))
            | np.isclose(
                active_solution, occupation_upper, rtol=1.0e-8, atol=1.0e-10
            )
        )
        refinement_success = False
        for refinement_index in range(active_states.size + 1):
            free = ~pinned
            if not np.any(free):
                optimizer_messages.append(
                    "no free states available for LM refinement"
                )
                break

            def free_residual(free_occupation: np.ndarray) -> np.ndarray:
                trial = active_solution.copy()
                trial[free] = free_occupation
                return residual(trial)[free]

            def free_jacobian(free_occupation: np.ndarray) -> np.ndarray:
                trial = active_solution.copy()
                trial[free] = free_occupation
                full = jacobian(trial)
                return full[np.ix_(free, free)]

            refinement = least_squares(
                free_residual,
                active_solution[free],
                jac=free_jacobian,
                method="lm",
                xtol=1.0e-12,
                ftol=1.0e-12,
                gtol=1.0e-12,
                max_nfev=maximum_evaluations,
            )
            function_evaluations += int(refinement.nfev)
            optimizer_messages.append(
                f"free-state LM refinement {refinement_index + 1}: "
                f"{refinement.message}"
            )
            candidate = active_solution.copy()
            candidate[free] = refinement.x
            below = free & (candidate < occupation_floor)
            above = free & (candidate > occupation_upper)
            if np.any(below) or np.any(above):
                active_solution[below] = occupation_floor
                active_solution[above] = occupation_upper
                pinned |= below | above
                optimizer_messages.append(
                    "active-set update pinned "
                    f"{int(np.count_nonzero(below))} lower and "
                    f"{int(np.count_nonzero(above))} upper states"
                )
                continue

            candidate_residual = float(np.max(np.abs(residual(candidate))))
            if candidate_residual < float(np.max(np.abs(initial_residual))):
                active_solution = candidate
                initial_residual = residual(active_solution)
            refinement_success = bool(refinement.success)
            break

    occupation = occupation_from_active(active_solution)
    dot, flux = population_rate(occupation, source1, source2, pre, post, rate)
    scaled_residual = residual(active_solution)
    capture = float(np.sum(flux[post == POST_CAPTURE]))
    capture_selector = post == POST_CAPTURE
    occupation_pair = occupation[source1] * occupation[source2]
    capture_energy = (
        float(np.sum(
            capture_energy_rate[capture_selector]
            * occupation_pair[capture_selector]
        ))
        if capture_energy_rate is not None else None
    )
    isotropic_capture_energy = (
        float(np.sum(capture_energy_rate[capture_selector]))
        if capture_energy_rate is not None else None
    )
    outer_exchange = float(np.sum(flux[post == POST_RESERVOIR]))
    connected_population_rate = float(np.sum(dot[connected]))
    internal_population_rate = float(np.sum(dot[~connected]))
    mass_identity = (
        float(np.sum(dot)) + capture + outer_exchange
    )
    normalization = max(capture + outer_exchange, float(np.sum(np.abs(dot))), 1.0e-300)
    jac = jacobian(active_solution)
    singular_values = np.linalg.svd(jac, compute_uv=False)
    rank_tolerance = max(jac.shape) * np.finfo(float).eps * max(
        float(singular_values[0]), 1.0
    )
    rank = int(np.count_nonzero(singular_values > rank_tolerance))
    condition = (
        float(singular_values[0] / singular_values[-1])
        if singular_values[-1] > 0.0 else math.inf
    )
    at_lower = active_solution <= max(10.0 * occupation_floor, 1.0e-300)
    at_upper = np.isclose(
        active_solution, occupation_upper, rtol=1.0e-8, atol=1.0e-10
    )
    maximum_residual = float(np.max(np.abs(scaled_residual)))
    gates = {
        "optimizer_success": bool(solution.success and refinement_success),
        "scaled_residual_le_tolerance": maximum_residual <= residual_tolerance,
        "full_jacobian_rank": rank == active_states.size,
        "no_upper_occupation_bound_hit": not bool(np.any(at_upper)),
        "positive_capture_current": capture > 0.0,
        "mass_identity_le_1e_10": abs(mass_identity) / normalization <= 1.0e-10,
    }
    result = {
        "model": model,
        "energy_moment_audit": ej_energy_ledger.audit(arrays, occupation, model),
        "status": "EJ_STEADY_SMOKE_PASS" if all(gates.values()) else "FAIL",
        "gates": gates,
        "optimizer_message": " | ".join(optimizer_messages),
        "function_evaluations": function_evaluations,
        "active_internal_states": int(active_states.size),
        "fixed_reservoir_states": int(np.count_nonzero(connected)),
        "inactive_internal_states_fixed_to_isotropic": int(np.count_nonzero(
            (~connected) & ~active
        )),
        "maximum_scaled_residual": maximum_residual,
        "residual_definition": (
            "maximum absolute net population rate divided by the isotropic "
            "interaction scale of that state"
        ),
        "residual_tolerance": residual_tolerance,
        "jacobian_rank": rank,
        "jacobian_dimension": int(active_states.size),
        "jacobian_condition_number": condition,
        "minimum_internal_occupation": float(np.min(occupation[active_states])),
        "maximum_internal_occupation": float(np.max(occupation[active_states])),
        "states_at_lower_bound": int(np.count_nonzero(at_lower)),
        "states_at_upper_bound": int(np.count_nonzero(at_upper)),
        "steady_capture_mdot_msun_per_myr": capture,
        "isotropic_capture_mdot_msun_per_myr": float(np.sum(
            rate[post == POST_CAPTURE]
        )),
        "steady_over_isotropic_capture": capture / max(float(np.sum(
            rate[post == POST_CAPTURE]
        )), 1.0e-300),
        "steady_capture_binding_energy_current_msun_kms2_per_myr": (
            capture_energy
        ),
        "steady_capture_mean_binding_energy_kms2": (
            capture_energy / capture
            if capture_energy is not None and capture > 0.0 else None
        ),
        "isotropic_capture_binding_energy_current_msun_kms2_per_myr": (
            isotropic_capture_energy
        ),
        "steady_over_isotropic_capture_binding_energy_current": (
            capture_energy / max(isotropic_capture_energy, 1.0e-300)
            if capture_energy is not None and isotropic_capture_energy is not None
            else None
        ),
        "outer_reservoir_return_msun_per_myr": outer_exchange,
        "connected_state_population_rate_msun_per_myr": connected_population_rate,
        "external_supply_to_hold_connected_states_msun_per_myr": (
            -connected_population_rate
        ),
        "internal_population_rate_msun_per_myr": internal_population_rate,
        "mass_identity_absolute_msun_per_myr": mass_identity,
        "mass_identity_relative": abs(mass_identity) / normalization,
        "note": (
            "This is a steady solution of the sampled EJ operator with the "
            "reporting-surface reservoir fixed. It is not an absolute closure "
            "until energy and angular resolution, independent seeds, reporting "
            "surfaces, and the production snapshot all converge."
        ),
    }
    return result, occupation


def state_rows(
    arrays: Dict[str, np.ndarray],
    metadata: dict,
    occupations: Dict[str, np.ndarray],
) -> list[dict]:
    nstates = int(metadata["state_count"])
    x_edges = np.asarray(arrays["x_edges"], float)
    j_edges = np.asarray(arrays["j_over_jlc_edges"], float)
    n_angular = j_edges.size - 1
    rows = []
    for state in range(nstates):
        cell = state // 2
        energy_bin = cell // n_angular
        angular_bin = cell % n_angular
        row = {
            "state": state,
            "domain": "reservoir" if state % 2 else "internal",
            "energy_bin": energy_bin,
            "x_lo": float(x_edges[energy_bin]),
            "x_hi": float(x_edges[energy_bin + 1]),
            "angular_bin": angular_bin,
            "j_over_jlc_lo": float(j_edges[angular_bin]),
            "j_over_jlc_hi": (
                float(j_edges[angular_bin + 1])
                if np.isfinite(j_edges[angular_bin + 1]) else "inf"
            ),
        }
        for model, occupation in occupations.items():
            row[f"occupation_{model}"] = float(occupation[state])
        rows.append(row)
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--operator", type=Path, required=True)
    parser.add_argument("--out-json", type=Path, required=True)
    parser.add_argument("--out-csv", type=Path, required=True)
    parser.add_argument(
        "--occupation-floor",
        type=float,
        default=1.0e-30,
        help=(
            "non-negative numerical floor for empty EJ cells; lower-bound hits "
            "are accepted only when the population-balance residual also passes"
        ),
    )
    parser.add_argument(
        "--occupation-upper",
        type=float,
        default=math.exp(5.0),
        help="upper bound on the occupation relative to the injected DF",
    )
    parser.add_argument("--rate-floor-fraction", type=float, default=1.0e-12)
    parser.add_argument("--residual-tolerance", type=float, default=1.0e-7)
    parser.add_argument("--maximum-evaluations", type=int, default=5000)
    args = parser.parse_args()
    arrays, metadata = load_operator(args.operator)
    models = {}
    occupations = {}
    for model in ("direct", "immediate"):
        models[model], occupations[model] = solve_model(
            arrays,
            metadata,
            model,
            occupation_floor=args.occupation_floor,
            occupation_upper=args.occupation_upper,
            rate_floor_fraction=args.rate_floor_fraction,
            residual_tolerance=args.residual_tolerance,
            maximum_evaluations=args.maximum_evaluations,
        )
    all_pass = all(model["status"] == "EJ_STEADY_SMOKE_PASS" for model in models.values())
    result = {
        "schema": "finite-angle-ej-steady-state-v2",
        "status": "EJ_STEADY_SMOKE_PASS" if all_pass else "FAIL",
        "absolute_closure_status": "REQUIRES_CONVERGENCE_AND_PRODUCTION_SNAPSHOT",
        "operator": args.operator.name,
        "operator_sha256": sha256_file(args.operator),
        "operator_metadata": metadata,
        "models": models,
        "model_spread_fraction_of_mean": abs(
            models["immediate"]["steady_capture_mdot_msun_per_myr"]
            - models["direct"]["steady_capture_mdot_msun_per_myr"]
        ) / max(0.5 * (
            models["immediate"]["steady_capture_mdot_msun_per_myr"]
            + models["direct"]["steady_capture_mdot_msun_per_myr"]
        ), 1.0e-300),
    }
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_csv.parent.mkdir(parents=True, exist_ok=True)
    rows = state_rows(arrays, metadata, occupations)
    with args.out_csv.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    result["occupation_csv_sha256"] = sha256_file(args.out_csv)
    args.out_json.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0 if all_pass else 2


if __name__ == "__main__":
    raise SystemExit(main())
